name: Problem Report
description: Something is wrong, but not as bad as a bug
title: "[Problem]"
labels: "problem"
body:
- type: input
  attributes:
    label: Version
    description: What version of TeXPaste are you running?
    placeholder: 1.1.0
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: What operating system are you using?
    placeholder: Windows 10
  validations:
    required: true
- type: textarea
  attributes:
    label: Problem Description
    description: Provide a list of steps to reproduce the problem and a detailed comparison of the expected and actual behavior.
  validations:
    required: true
